USE [master]
GO
/****** Object:  Database [NewShoreAir]    Script Date: 1/06/2023 12:02:22 a. m. ******/
CREATE DATABASE [NewShoreAir]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NewShoreAir', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\NewShoreAir.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NewShoreAir_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\NewShoreAir_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [NewShoreAir] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NewShoreAir].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [NewShoreAir] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [NewShoreAir] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [NewShoreAir] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [NewShoreAir] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [NewShoreAir] SET ARITHABORT OFF 
GO
ALTER DATABASE [NewShoreAir] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [NewShoreAir] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [NewShoreAir] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [NewShoreAir] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [NewShoreAir] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [NewShoreAir] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [NewShoreAir] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [NewShoreAir] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [NewShoreAir] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [NewShoreAir] SET  DISABLE_BROKER 
GO
ALTER DATABASE [NewShoreAir] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [NewShoreAir] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [NewShoreAir] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [NewShoreAir] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [NewShoreAir] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [NewShoreAir] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [NewShoreAir] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [NewShoreAir] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [NewShoreAir] SET  MULTI_USER 
GO
ALTER DATABASE [NewShoreAir] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [NewShoreAir] SET DB_CHAINING OFF 
GO
ALTER DATABASE [NewShoreAir] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [NewShoreAir] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [NewShoreAir] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [NewShoreAir] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [NewShoreAir] SET QUERY_STORE = OFF
GO
USE [NewShoreAir]
GO
/****** Object:  Table [dbo].[Flight]    Script Date: 1/06/2023 12:02:22 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Flight](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IdTransport] [int] NULL,
	[Origin] [nvarchar](5) NULL,
	[Destination] [nvarchar](5) NULL,
	[Price] [decimal](18, 0) NULL,
 CONSTRAINT [PK_Flight] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Journey]    Script Date: 1/06/2023 12:02:22 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Journey](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Origin] [nvarchar](50) NULL,
	[Destination] [nvarchar](50) NULL,
	[Price] [decimal](18, 0) NULL,
 CONSTRAINT [PK_Journey] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[JourneyFlight]    Script Date: 1/06/2023 12:02:22 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[JourneyFlight](
	[IdJourney] [int] NOT NULL,
	[IdFlight] [int] NOT NULL,
 CONSTRAINT [PK_JourneyFlight] PRIMARY KEY CLUSTERED 
(
	[IdJourney] ASC,
	[IdFlight] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Transport]    Script Date: 1/06/2023 12:02:22 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Transport](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Carrier] [nvarchar](50) NULL,
	[NumberTr] [nvarchar](50) NULL,
 CONSTRAINT [PK_Transport] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Flight]  WITH CHECK ADD  CONSTRAINT [FK_Flight_Transport] FOREIGN KEY([IdTransport])
REFERENCES [dbo].[Transport] ([Id])
GO
ALTER TABLE [dbo].[Flight] CHECK CONSTRAINT [FK_Flight_Transport]
GO
ALTER TABLE [dbo].[JourneyFlight]  WITH CHECK ADD  CONSTRAINT [FK_JourneyFlight_Flight] FOREIGN KEY([IdFlight])
REFERENCES [dbo].[Flight] ([Id])
GO
ALTER TABLE [dbo].[JourneyFlight] CHECK CONSTRAINT [FK_JourneyFlight_Flight]
GO
ALTER TABLE [dbo].[JourneyFlight]  WITH CHECK ADD  CONSTRAINT [FK_JourneyFlight_Journey] FOREIGN KEY([IdJourney])
REFERENCES [dbo].[Journey] ([Id])
GO
ALTER TABLE [dbo].[JourneyFlight] CHECK CONSTRAINT [FK_JourneyFlight_Journey]
GO
USE [master]
GO
ALTER DATABASE [NewShoreAir] SET  READ_WRITE 
GO
